# Generated by Django 4.2.11 on 2024-05-30 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('index_symbol', models.CharField(max_length=200)),
                ('data_static', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.datastatic')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
